version: '3.5'
services:
    ts-gateway:
        hostname: ts-gateway-php
        build: docker/php-fpm
        container_name: ts-gateway-php
        volumes:
            - ./:/var/www/app
        expose:
            - 9000
        networks:
            - gateway
            - proxy
            - default
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.ts-gateway.rule=Host(`gateway.local`)"
#            - "traefik.http.services.ts-gateway.loadbalancer.server.port=801"

    ts-gateway-nginx:
        hostname: ts-gateway-nginx
        build: docker/nginx
        container_name: ts-gateway-nginx
        ports:
            - '8081:81'
#        command:
#            - --port=8081 # Our service listens on 8081 labels:

        expose:
            - 80
            - 443
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - ts-gateway
        networks:
            - gateway
            - proxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ts-gateway-nginx.rule=Host(`gateway.local`)"
#            - "traefik.http.routers.ts-gateway-nginx.tls=false"
            - "traefik.docker.network=default"
            - "traefik.http.services.ts-gateway-nginx.loadbalancer.server.port=801"

networks:
    default:
        name: ts-external-network
        external: true
    gateway:
        name: gateway
        driver: bridge
    proxy:
        name: proxy
        external: true
