# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            FOS\ElasticaBundle\Elastica\Index $accountIndex: '@fos_elastica.index.accounts'
            FOS\ElasticaBundle\Elastica\Index $productIndex: '@fos_elastica.index.products'
            FOS\ElasticaBundle\Index\MappingBuilder $mappingBuilder: '@fos_elastica.mapping_builder'
            FOS\ElasticaBundle\Index\AliasProcessor $aliasProcessor: '@fos_elastica.alias_processor'
            string $accountAlias: '%env(ELASTICSEARCH_ACCOUNTS_INDEX)%'
            string $productAlias: '%env(ELASTICSEARCH_PRODUCTS_INDEX)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
