version: '3.5'
services:
    ts-bo:
        hostname: ts-bo-php
        build: docker/php-fpm
        container_name: ts-bo-php
        volumes:
            - ./:/var/www/app
        expose:
            - 9000
        networks:
            - gateway
            - proxy
            - default

    ts-bo-nginx:
        hostname: ts-bo-nginx
        build: docker/nginx
        container_name: ts-bo-nginx
        ports:
            - '8080:80'
        expose:
            - 80
            - 443
        networks:
            - gateway
            - proxy
            - default
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - ts-bo
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.ts-bo-nginx.rule=Host(`backoffice.local`)"
            - "traefik.http.routers.ts-bo-nginx.tls=false"
            - "traefik.docker.network=proxy"
networks:
    default:
        name: ts-external-network
        external: true
    gateway:
        name: gateway
        driver: bridge
    proxy:
        name: proxy
        external: true

